services:
  crypto_trader:
    build:
      context: ./app
      dockerfile: Dockerfile
    container_name: crypto_trader
    restart: always
    env_file:
      - .env
    networks:
      - shared_db_net

networks:
  shared_db_net:
    external: true
    name: shared_db_net